#!/usr/bin/env python3
from __future__ import annotations
import csv,json,struct,hashlib
from collections import defaultdict,Counter
from pathlib import Path
ROOT=Path('/home/zhihan/research/Basin_C1');HERE=ROOT/'diagnostics/orthoflow3_analytic_basin_margin_learning_v1';POINT=ROOT/'diagnostics/orthoflow3_true_t0_point_learning_v1';PACT=ROOT/'diagnostics/orthoflow3_t0_pact_training_readiness_v1';CONT=ROOT/'diagnostics/orthoflow3_t0_eta_continuity_cross_transfer_v1'
HERE.mkdir(parents=True,exist_ok=True)
def key(v):return b''.join(struct.pack('<d',float(x)) for x in v).hex()
def add(store,sid,v,succ,trials,dead,to,coll,source,phase,independent=False):
 k=(sid,key(v));r=store.get(k)
 if r is None:
  r=store[k]={'state_id':sid,'eta1':float(v[0]),'eta2':float(v[1]),'eta3':float(v[2]),'successes':int(succ),'trials':int(trials),'deadlock':int(dead),'timeout':int(to),'collision':int(coll),'sources':set(),'phases':set(),'independent_sources':set()}
 else:
  # Exact duplicate Q64 results must agree; retain the fullest exact record.
  if int(trials)>=64 and r['trials']>=64:assert int(succ)==r['successes'],(k,succ,r['successes'])
  if int(trials)>r['trials']:r.update(successes=int(succ),trials=int(trials),deadlock=int(dead),timeout=int(to),collision=int(coll))
 r['sources'].add(source);r['phases'].add(phase)
 if independent:r['independent_sources'].add(source)

split=json.load(open(POINT/'final_source_split.json'));states={r['state_id']:r for r in split['states']};store={}
# Dense old-eight aggregate, already deduplicated exact Q64.
for r in csv.DictReader(open(PACT/'exact_q64_manifest.csv')):
 if r['state_id'] not in states or str(r['Q64_available']).lower()!='true' or int(r['trials'])<64:continue
 phase=r['phases'];src=r['sources'];ind=('coverage64' in phase or 'shape_targeted' in src or 'completion_G_' in phase)
 add(store,r['state_id'],[r['eta1'],r['eta2'],r['eta3']],r['successes'],64,r['deadlock'],r['timeout'],r['collision'],'dense8_'+src,phase,ind)
# New-32 exact point-search groups.
raw=defaultdict(dict)
for p in sorted((POINT/'state_runs').glob('*/raw/pilot_rollouts.jsonl')):
 for line in open(p):
  if not line.strip():continue
  r=json.loads(line);raw[(r['state_id'],key(r['eta']))][int(r['future_index'])]=r
for (sid,_),g in raw.items():
 if sid not in states or not all(i in g for i in range(64)):continue
 rr=[g[i] for i in range(64)];add(store,sid,rr[0]['eta'],sum(bool(x['success']) for x in rr),64,sum(x['outcome']=='deadlock' for x in rr),sum(x['outcome']=='timeout' for x in rr),sum(x['outcome']=='collision' for x in rr),'point_label_search','q64_promotion',False)
# Frozen targeted cross-transfers; new exact coordinates are independent neighbor probes.
for r in csv.DictReader(open(CONT/'cross_transfer_results.csv')):
 sid=r['destination_state'];v=[r['eta1'],r['eta2'],r['eta3']];k=(sid,key(v));isnew=k not in store
 add(store,sid,v,r['successes'],64,r['deadlock'],r['timeout'],r['collision'],'cross_transfer_'+r['eta_source_state'],'cross_transfer_q64',isnew)
# Independent VAL neighbor-target probes generated by this experiment, if complete.
vg=defaultdict(dict)
for p in sorted((HERE/'raw/val_neighbor_q64').glob('shard*.jsonl')):
 for line in open(p):
  if not line.strip():continue
  r=json.loads(line);vg[(r['state_id'],key(r['eta']))][int(r['future_index'])]=r
for (sid,_),g in vg.items():
 if not all(i in g for i in range(64)):continue
 rr=[g[i] for i in range(64)];fit_acquisition=int(rr[0]['mode_index'])%2==0;src='val_neighbor_fit' if fit_acquisition else 'val_neighbor_validation'
 add(store,sid,rr[0]['eta'],sum(bool(x['success']) for x in rr),64,sum(x['outcome']=='deadlock' for x in rr),sum(x['outcome']=='timeout' for x in rr),sum(x['outcome']=='collision' for x in rr),src,'val_neighbor_target_q64',not fit_acquisition)

# Frozen deterministic secondary holdout: one exact point-search B63 coordinate
# per sparse VAL state. This is never used to fit that state's representation.
for sid,smeta in states.items():
 if smeta['split']!='val' or not sid.startswith('T0_POINT'):continue
 cand=sorted((r for (ss,_),r in store.items() if ss==sid and r['successes']>=63 and 'point_label_search' in r['sources']),key=lambda r:(r['eta1'],r['eta2'],r['eta3']))
 if cand:cand[-1]['independent_sources'].add('deterministic_val_point_holdout')

allout=[]
for r in store.values():
 r['sources']=';'.join(sorted(r['sources']));r['phases']=';'.join(sorted(r['phases']));r['independent_sources']=';'.join(sorted(r['independent_sources']))
 r['split']=states[r['state_id']]['split'];r['source_group']=states[r['state_id']]['source_group'];r['Q64']=r['successes']/64;r['B63']=r['successes']>=63
 r['evidence_role']='independent_positive' if r['B63'] and r['independent_sources'] else ('fit_positive' if r['B63'] else 'hard_negative')
 allout.append(r)
test_quarantined=[r for r in allout if r['split']=='test'];out=[r for r in allout if r['split']!='test']
fields=['state_id','source_group','split','eta1','eta2','eta3','successes','trials','Q64','B63','deadlock','timeout','collision','evidence_role','sources','phases','independent_sources']
with open(HERE/'exact_q64_inventory.csv','w',newline='') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(sorted(out,key=lambda r:(r['split'],r['state_id'],r['eta1'],r['eta2'],r['eta3'])))
summary=[]
for sid in states:
 if states[sid]['split']=='test':continue
 rr=[r for r in out if r['state_id']==sid];c=Counter(r['evidence_role'] for r in rr)
 summary.append({'state_id':sid,'source_group':states[sid]['source_group'],'split':states[sid]['split'],'exact_q64_eta':len(rr),'B63':sum(r['B63'] for r in rr),'non_B63':sum(not r['B63'] for r in rr),
  'fit_positive':c['fit_positive'],'independent_positive':c['independent_positive'],'hard_negative':c['hard_negative']})
with open(HERE/'state_evidence_summary.csv','w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(summary[0]));w.writeheader();w.writerows(summary)
reuse={'unique_exact_q64_state_eta_used':len(out),'B63_used':sum(r['B63'] for r in out),'non_B63_used':sum(not r['B63'] for r in out),'test_records_quarantined_not_exported':len(test_quarantined),'by_split':{},'source_files':[str(PACT/'exact_q64_manifest.csv'),str(POINT/'state_runs'),str(CONT/'cross_transfer_results.csv')]}
for sp in ('train','val'):
 z=[r for r in out if r['split']==sp];reuse['by_split'][sp]={'eta':len(z),'B63':sum(r['B63'] for r in z),'non_B63':sum(not r['B63'] for r in z),'states':len({r['state_id'] for r in z})}
(HERE/'cached_reuse_manifest.json').write_text(json.dumps(reuse,indent=2)+'\n')
print(json.dumps(reuse,indent=2));print('STATE SUMMARY')
for r in summary:print(r)
