#!/usr/bin/env python3
"""Freeze an outcome-blind true-t0 cohort and exact h0 conditioning."""
from __future__ import annotations
import csv,hashlib,importlib.util,json,shutil,sys
from pathlib import Path
import jax,jax.numpy as jnp
import numpy as np
ROOT=Path('/home/zhihan/research/Basin_C1');SYSROOT=Path('/home/zhihan/research/02_C1_Toy_GiveWay');HERE=ROOT/'diagnostics/orthoflow3_t0_basin_structure_v1';SOURCE=ROOT/'diagnostics/orthoflow3_continuous_inner_ball_pilot6_v1/continuous_pilot6.py';FRESH=ROOT/'diagnostics/orthoflow3_basin_margin_learning_v1/fresh_wide_manifest.json';BASIS=ROOT/'diagnostics/double_bottleneck_eta_basis_redesign/tools/bases.py';FUTURE_ROOT=2026092811;PERM_SEED=2026092810
for p in (SYSROOT,ROOT):sys.path.insert(0,str(p))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def dump(p,x):Path(p).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def write_csv(p,rr):
 with open(p,'w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rr[0]));w.writeheader();w.writerows(rr)
def load_mod():
 spec=importlib.util.spec_from_file_location('t0_geom_source',SOURCE);m=importlib.util.module_from_spec(spec);sys.modules[spec.name]=m;spec.loader.exec_module(m);return m
def main():
 HERE.mkdir(parents=True,exist_ok=True);(HERE/'states').mkdir(exist_ok=True);(HERE/'anchor_runs').mkdir(exist_ok=True);(HERE/'synthetic_qdir/raw').mkdir(parents=True,exist_ok=True);(HERE/'empty_prior').mkdir(exist_ok=True);(HERE/'logs').mkdir(exist_ok=True)
 if sha(BASIS)!='51c2cbcc235a5ba9db6f73b3d449e0bc631bfbb0e1ed3184c4fed97c8fa01c38':raise RuntimeError('basis hash')
 fresh=json.load(open(FRESH));perm=np.random.default_rng(PERM_SEED).permutation(len(fresh['episodes']));ordered=[fresh['episodes'][int(i)] for i in perm];selected=ordered[:8];reserve=ordered[8:12]
 # Freeze no-expansion before outcomes: 12-state worst-case + controller audits exceeds 25k.
 preflight={'permutation_seed':PERM_SEED,'eligible':len(ordered),'primary_count':8,'reserve_count':4,'expansion_predeclared':True,'expansion_condition':'all first 8 complete AND projected total <= hard caps','expansion_frozen_decision':'DO_NOT_EXPAND_TO_12','reason':'outcome-blind worst-case projection exceeds 25,000 continuations','components_8':{'common48_plus_zero_screen':8*49*8,'extension48_worst_case':8*48*8,'center_promotion_allowance':8*3*56,'ray_screen_bisection_allowance':8*18*7*8,'limiting_B63':8*8*56,'inside_screen_plus_four_promotions':8*(12*8+4*56),'zero_B63_increment':8*56,'three_controller_Q64':8*3*64},'projected_8_worst_case':None,'projected_12_worst_case':None,'hard_cap_continuations':25000,'hard_cap_steps':7000000}
 preflight['projected_8_worst_case']=sum(preflight['components_8'].values());preflight['projected_12_worst_case']=round(preflight['projected_8_worst_case']*1.5);dump(HERE/'cost_preflight.json',preflight)
 mod=load_mod();norm,affine,scale,lo,hi,verts,tv,hull,eq=mod.geometry();cloud=mod.sobol_bridge(eq,affine,scale,96);write_csv(HERE/'t0_eta_cloud.csv',cloud);write_csv(HERE/'ebridge_sobol_sequence.csv',cloud);shutil.copy2(ROOT/'diagnostics/orthoflow3_continuous_inner_ball_pilot6_v1/ebridge_definition.json',HERE/'ebridge_definition.json');shutil.copy2(ROOT/'diagnostics/orthoflow3_continuous_inner_ball_pilot6_v1/ebridge_halfspaces.csv',HERE/'ebridge_halfspaces.csv');shutil.copy2(ROOT/'diagnostics/orthoflow3_continuous_inner_ball_pilot6_v1/eta_normalization.json',HERE/'eta_normalization.json');shutil.copy2(ROOT/'diagnostics/orthoflow3_continuous_inner_ball_pilot6_v1/frozen_ray_directions.csv',HERE/'frozen_ray_directions.csv')
 from diagnostics.gphi_training_dataset_v2.build_states import save_full
 from diagnostics.gphi_training_dataset_startup_complete_v1.startup_feature_builder import StartupAwareFeatureBuilder
 from diagnostics.single_segment_recovery_training_v1.state_machine import FiniteHistoryView
 from diagnostics.success_basin_multimodality.exact_projector import project_velocity_with_retry
 from single_integrator.cbf import CBFConfig,barrier_constraints
 from single_integrator.environment import Config,GiveWayEnv,bounded_nominal
 from single_integrator.evaluate import load_policy
 integ=json.load(open(ROOT/'diagnostics/gphi_fixed_d_eta_predictor_v1/integrity_audit.json'));config=Config(**integ['environment']);cbf=CBFConfig(**integ['cbf']);policy,_=load_policy(SYSROOT/'baseline_309_314/checkpoints/seed0/ckpt_0025000.pkl');sample=jax.jit(lambda obs,key:policy.sample_actions(obs[None],seed=key)[0]);flow_seed=int(fresh['flow_randomness']['root_seed']);states=[];features=[]
 for rank,ep in enumerate(selected):
  sid=f'T0_WIDE_perm{rank:02d}_ep{int(ep["episode_index"]):04d}';env=GiveWayEnv(config);env.reset(np.asarray(ep['initial_positions'],float));p=HERE/'states'/f'{sid}.npz';save_full(p,env);rng=int(ep['rollout_id']);base=jax.random.fold_in(jax.random.PRNGKey(flow_seed),rng);key=jax.random.fold_in(base,0);act=np.asarray(sample(jnp.asarray(env.observation(),dtype=jnp.float32),key));flow=bounded_nominal(act,config.max_speed);A,lower,_=barrier_constraints(env.snapshot(),cbf);safe,_,_,_=project_velocity_with_retry(flow,A,lower,config.max_speed,cbf);h,_=StartupAwareFeatureBuilder().build(FiniteHistoryView(env),{'u_flow':flow,'u_safe':safe},config,cbf);h=np.asarray(h,dtype=np.float64);features.append(h);states.append({'state_id':sid,'source_group':ep['source_id'],'source_trajectory':ep['source_id'],'split':'audit','absolute_step':0,'true_t0':True,'initial_positions':ep['initial_positions'],'fresh_episode_index':ep['episode_index'],'fresh_rollout_id':ep['rollout_id'],'state_file':str(p),'state_sha256':sha(p),'feature_index':rank,'feature_sha256':hashlib.sha256(h.tobytes()).hexdigest(),'flow_seed':flow_seed,'rng_namespace':rng,'h_conditioning_identifier':f'{sid}__flow{flow_seed}__episode{rng}','current_flow_key_semantics':f'fold_in(fold_in(PRNGKey({flow_seed}),{rng}),0)','future_root_seed':FUTURE_ROOT})
 np.savez_compressed(HERE/'synthetic_qdir/conditioning_features.npz',features=np.asarray(features));dump(HERE/'synthetic_qdir/eligible_state_manifest.json',{'selected_states':states});dump(HERE/'t0_state_manifest.json',{'schema':'orthoflow3_t0_basin_structure_v1','selection':'deterministic permutation of frozen independent fresh-WIDE ICs; outcome blind','permutation_seed':PERM_SEED,'source_manifest':str(FRESH),'source_manifest_sha256':sha(FRESH),'attempted_states':states,'reserved_not_executed':[{'rank':8+i,'episode_index':x['episode_index'],'source_id':x['source_id']} for i,x in enumerate(reserve)],'frozen_before_new_outcomes':True})
 dump(HERE/'source_diversity_audit.json',{'states':8,'independent_source_groups':8,'duplicate_source_groups':0,'temporal_neighbors_used':False,'all_absolute_step_zero':True})
 dump(HERE/'conditioning_semantics.json',{'quantity':'Q(h0,eta)','h0':'h(z0,xi0), exact episode-start feature with current Flow realization fixed','current_flow':'fixed by flow_seed/rng_namespace/absolute_step in each state manifest row','future_flow':f'resampled by future_index from state-token-folded root {FUTURE_ROOT}','eta':'selected once at t0 and fixed through episode','basis':'OrthoFlow3 recomputed each physical step','second_projection':True,'h_variants_averaged':False})
 dump(HERE/'cache_reuse_audit.json',{'exact_compatible_continuations':0,'records_scanned':'prior fresh-WIDE and diagnostic namespaces inspected conceptually','reason':'selected t0 h/xi0 identities have no prior 8/64-seed outcomes under future_root 2026092811; prior fresh-WIDE has one matched episode stream rather than this continuation-seed semantics','new_rollouts_launched_during_inventory':0})
 (HERE/'protocol.md').write_text('# OrthoFlow3 true-t0 basin structure audit v1\n\nEight genuine episode-start states are frozen by an outcome-blind permutation of an independent fresh-WIDE manifest. The accepted continuous E_bridge ball protocol is reused with a 48-point common cloud, one predeclared 48-point extension, 18 frozen rays, B63 limiting-radius confirmation, kappa=0.85, 12 independent inside points, and four mandatory B63 points at approximately .25/.60/.90/.97 radius. Eta zero is B63-tested for every state. No model is trained and no label/controller semantics are modified.\n')
 print(json.dumps({'selected':[x['state_id'] for x in states],'projected':preflight,'cloud_sha256':sha(HERE/'t0_eta_cloud.csv')},indent=2))
if __name__=='__main__':main()
