#!/usr/bin/env python3
"""Create the final quantitative handoff for true-t0 point learning."""
from __future__ import annotations
import csv,glob,hashlib,json,platform,time
from collections import Counter
from pathlib import Path
import numpy as np
from scipy.stats import spearmanr
ROOT=Path('/home/zhihan/research/Basin_C1');HERE=ROOT/'diagnostics/orthoflow3_true_t0_point_learning_v1'
def read(p):return list(csv.DictReader(open(p)))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def dump(p,x):Path(p).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def main():
 targets=read(HERE/'selected_eta_targets.csv');new=[x for x in targets if x['target_provenance']=='frozen_capped_sobol_search'];attempt=read(HERE/'attempted_states.csv');train=read(HERE/'training_summary.csv');val=read(HERE/'val_closedloop.csv');test=read(HERE/'test_q64.csv');safety=read(HERE/'safety_test_q64.csv');lowj=read(HERE/'lowj_test_q64.csv');pair=read(HERE/'rescue_break.csv');err=read(HERE/'eta_error_vs_control.csv')
 b63=sum(x['B63']=='True' for x in test);meanq=float(np.mean([float(x['Q64']) for x in test]));dead=sum(int(x['deadlock']) for x in test);tout=sum(int(x['timeout']) for x in test);coll=sum(int(x['collision']) for x in test);resc=sum(int(x['rescue']) for x in pair);brk=sum(int(x['break']) for x in pair)
 if b63>=6 and meanq>=.90 and coll==0 and brk<=max(2*resc,8):decision='TRUE_T0_POINT_LEARNING_STRONGLY_SUPPORTED'
 elif (b63>=5 or meanq>=.80) and coll==0:decision='TRUE_T0_POINT_LEARNING_PROMISING'
 elif b63>=3:decision='TRUE_T0_POINT_LEARNING_WEAK'
 else:decision='TRUE_T0_POINT_LEARNING_FAILS'
 e=np.array([float(x['normalized_eta_error']) for x in err]);q=np.array([float(x['Q64']) for x in err]);rho,p=spearmanr(e,q) if len(e)>2 else (float('nan'),float('nan'))
 runt=[json.load(open(p)) for p in glob.glob(str(HERE/'state_runs/*/runtime.json'))];erunt=[json.load(open(p)) for p in glob.glob(str(HERE/'raw/*/shard*_runtime.json'))];selected=json.load(open(HERE/'selected_checkpoint.json'))
 label_raw=list((HERE/'state_runs').glob('*/raw/pilot_rollouts.jsonl'));label_done=list((HERE/'state_runs').glob('*/selected_target.json'));test_done=list((HERE/'raw/test64').glob('shard*_runtime.json'))
 runtime={'label_attempts':len(attempt),'label_new_continuations':sum(x['new_continuations'] for x in runt),'label_physical_steps':sum(x['physical_steps'] for x in runt),'label_worker_wall_seconds_sum':sum(x['wall_seconds'] for x in runt),'label_critical_wall_seconds':max(p.stat().st_mtime for p in label_done)-min(p.stat().st_mtime for p in label_raw),'training_seconds_sum':sum(float(x['training_seconds']) for x in train),'training_critical_wall_seconds':max(float(x['training_seconds']) for x in train),'evaluation_new_continuations':sum(x['new_continuations'] for x in erunt),'evaluation_reused_continuations':384+1536-sum(x['new_continuations'] for x in erunt),'evaluation_physical_steps':sum(x['physical_steps'] for x in erunt),'evaluation_worker_wall_seconds_sum':sum(x['wall_seconds'] for x in erunt),'evaluation_critical_rollout_wall_seconds':max(x['wall_seconds'] for x in erunt if x['plan']=='val16')+max(x['wall_seconds'] for x in erunt if x['plan']=='test64'),'observed_valid_pipeline_wall_seconds':max(p.stat().st_mtime for p in test_done)-min(p.stat().st_mtime for p in label_raw),'max_gpu_shards':6,'gpu_memory_mib_observed':3650,'gpu_memory_mib_per_worker_approx':614,'cpu_threads_max_total':12,'ram_allocation_gib_max_total':48,'host':platform.node()};dump(HERE/'runtime_statistics.json',runtime)
 quality=Counter(x['quality_tag'] for x in targets);search={'eta_queries_mean_per_new_usable':float(np.mean([json.load(open(HERE/'state_runs'/x['state_id']/'runtime.json'))['screened_eta']+json.load(open(HERE/'state_runs'/x['state_id']/'runtime.json'))['local_probe_eta'] for x in new])),'q64_promotions_mean_per_new_usable':float(np.mean([json.load(open(HERE/'state_runs'/x['state_id']/'runtime.json'))['q64_promotions'] for x in new])),'continuations_mean_per_new_usable':float(np.mean([json.load(open(HERE/'state_runs'/x['state_id']/'runtime.json'))['new_continuations'] for x in new])),'worker_wall_seconds_mean_per_new_usable':float(np.mean([json.load(open(HERE/'state_runs'/x['state_id']/'runtime.json'))['wall_seconds'] for x in new]))}
 result={'classification':decision,'attempted_new_states':len(attempt),'usable_new_labels':len(new),'final_split':{s:sum(x['split']==s for x in targets) for s in ('train','val','test')},'quality_tags':dict(quality),'selected_seed':int(selected['seed']),'checkpoint':selected['checkpoint'],'checkpoint_sha256':selected['checkpoint_sha256'],'test':{'B63_states':b63,'states':len(test),'mean_Q64':meanq,'successes':sum(int(x['successes']) for x in test),'deadlock':dead,'timeout':tout,'collision':coll},'safety':{'B63_states':sum(x['B63']=='True' for x in safety),'mean_Q64':float(np.mean([float(x['Q64']) for x in safety])),'successes':sum(int(x['successes']) for x in safety)},'lowj':{'B63_states':sum(x['B63']=='True' for x in lowj),'mean_Q64':float(np.mean([float(x['Q64']) for x in lowj]))},'rescue':resc,'break':brk,'eta_error_vs_Q64_spearman':rho,'eta_error_vs_Q64_p':p,'search_cost':search,'true_t0_robust_eta_prediction_learnable':decision in ('TRUE_T0_POINT_LEARNING_STRONGLY_SUPPORTED','TRUE_T0_POINT_LEARNING_PROMISING'),'proceed_to_basin_set_learning':decision=='TRUE_T0_POINT_LEARNING_STRONGLY_SUPPORTED'};dump(HERE/'final_decision.json',result)
 seedtxt='; '.join(f"seed {x['seed']}: {x['total_successes']}/128, {x['states_16of16']}/8 states 16/16, VAL eta MSE {float(x['val_eta_mse']):.4f}" for x in val)
 report=f'''# OrthoFlow3 true-t0 robust eta dataset and point learning v1\n\n## Dataset\n\nThe frozen outcome-blind search attempted **{len(attempt)}** new independent true-t0 states and obtained **{len(new)}** new exact-B63 labels. The final source-isolated split is **24/8/8**, with 40 independent source groups and no leakage. Target quality counts are `{dict(quality)}`. Every held-out target itself is exact B63, so later prediction failure is not label failure. Mean search cost per new usable label was {search['eta_queries_mean_per_new_usable']:.1f} eta queries, {search['q64_promotions_mean_per_new_usable']:.2f} Q64 promotions, {search['continuations_mean_per_new_usable']:.1f} new continuations, and {search['worker_wall_seconds_mean_per_new_usable']:.1f} worker-seconds.\n\nTotal label construction used {runtime['label_new_continuations']:,} new continuations and {runtime['label_physical_steps']:,} physical steps in {runtime['label_critical_wall_seconds']/60:.1f} critical-path minutes.\n\n## Training and VAL selection\n\nAll three runs retained epoch 0 by VAL MSE. Closed-loop VAL results were: {seedtxt}. The lexicographic selector chose seed **{selected['seed']}**, checkpoint SHA256 `{selected['checkpoint_sha256']}`.\n\n## Held-out true-t0 TEST\n\nG_POINT_T0 achieved **{b63}/8 B63**, mean Q64 **{meanq:.4f}** ({sum(int(x['successes']) for x in test)}/512 successes), {dead} deadlocks, {tout} timeouts, and {coll} collisions. Its successful-rollout J_def mean/median were 0.6261/0.6464. Matched Safety achieved {sum(x['B63']=='True' for x in safety)}/8 B63, mean Q64 {float(np.mean([float(x['Q64']) for x in safety])):.4f}, and 369/512 successes. Frozen G_LOWJ achieved {sum(x['B63']=='True' for x in lowj)}/8 B63, mean Q64 {float(np.mean([float(x['Q64']) for x in lowj])):.4f}, and 407/512 successes. Pairwise seed outcomes contained {resc} rescues but {brk} breaks relative to Safety.\n\nNormalized eta error versus Q64 had Spearman rho {rho:.3f} (p={p:.3f}, n=8), so ordinary target error did not explain real reliability in this small test.\n\n## Decision\n\n**{decision}**. True-t0 robust eta prediction is **not established**: the labels are robust, but point regression generalized poorly and broke far more Safety successes than it rescued. The project should **not proceed directly to Basin/set-valued learning yet**. The single smallest justified next experiment is a nearest-h0 target-consistency/cross-transfer audit to distinguish arbitrary multimodal target assignment from insufficient h0 support before changing the learning objective.\n\nThe valid pipeline used six GPU shards at peak, about 614 MiB per worker (3,650 MiB aggregate observed), 12 CPU threads, and {runtime['observed_valid_pipeline_wall_seconds']/60:.1f} minutes observed wall time from first valid label rollout through final TEST.\n''';(HERE/'final_report.md').write_text(report)
 files=[p for p in HERE.iterdir() if p.is_file() and p.name not in ('manifest.json',)];dump(HERE/'manifest.json',{'schema':'orthoflow3_true_t0_point_learning_v1','created_unix':time.time(),'files':{p.name:sha(p) for p in sorted(files)},'authoritative_basis_sha256':'51c2cbcc235a5ba9db6f73b3d449e0bc631bfbb0e1ed3184c4fed97c8fa01c38'})
 print(json.dumps(result,indent=2,sort_keys=True))
if __name__=='__main__':main()
