"""Outcome-blind independent-family support expansion and sealed confirmation.

The source geometry/controller family stays fixed. This isolates state support
from architecture changes. New TRAIN/VAL and a sealed independent TEST are
generated by the native physical IC generator; no critic/generator scores or
success filtering determine inclusion. The final TEST request is not executed
until models and selection rules have been frozen.
"""
import argparse,copy,json
from pathlib import Path
from . import seed_replication as engine
from shared_rollout_db.src.rollout_db import connect,transaction,canonical,uid
from new_benchmark_common.basin_dataset_v1 import content_hash
from ring_exchange.environment import Config,sample_instance

OUT=Path(__file__).resolve().parent/'state_support'
EXP='exp_orthoflow3_rootcause_state_support_v1'
read=engine.read;write=engine.write

def prepare():
    if (OUT/'protocol.json').exists():raise FileExistsError('Independent state protocol frozen')
    source=read(engine.OUT/'states.json')[0]
    p=copy.deepcopy(read(engine.OUT/'protocol.json'))
    cfg=Config(**read(OUT.parent.parent/'ring_exchange_stage1/base_u_v10_local_dataset/manifest.json')['scenario_config'])
    eta_rows=read(engine.OUT/'pairs.json')[:2];states=[];pairs=[];test_requests=[]
    assert [e['eta_index'] for e in eta_rows]==[10,15]
    with connect() as db,transaction(db):
        original=db.execute('SELECT * FROM state WHERE state_uid=?',(source['uid'],)).fetchone()
        db.execute('INSERT OR IGNORE INTO experiment(experiment_uid,name,path,start_time,metadata_json) VALUES(?,?,?,CURRENT_TIMESTAMP,?)',
            (EXP,'independent_source_state_support_expansion',str(OUT),canonical({'source_only':True,'target_LOSO_labels_used':False})))
        for split,count,native_split in (('train',160,'train'),('validation',32,'development'),('test',64,'test')):
          for j in range(count):
            seed=940031000+j;instance=sample_instance(seed,native_split,cfg)
            physical={k:getattr(instance,k).tolist() for k in ('positions','velocities','goals')};physical['timestep']=0
            ch=content_hash(physical);state_uid=uid('state',{'scenario':original['scenario_uid'],'content':ch})
            assert db.execute('SELECT 1 FROM state WHERE state_uid=?',(state_uid,)).fetchone() is None,'Not genuinely new physical family'
            s=dict(alias=f'ROOTCAUSE_SUPPORT_{split}_{seed}',content_hash=ch,index=len(states),repair_index=len(states),
                physical=physical,provenance=dict(generator='ring_exchange.environment.sample_instance',split=native_split,
                    initial_seed=seed,outcome_blind=True,controller_source_only=True,task='rootcause_state_support'),
                rollout_id=f'rootcause_support:{split}:{seed}',source_dataset_split=native_split,
                source_group=f'rootcause_support:{split}:{seed}',split=split,uid=state_uid)
            geometry=json.loads(original['goals_geometry_json']);geometry['goals']=physical['goals']
            db.execute('INSERT INTO state(state_uid,scenario_uid,source_group,content_hash,physical_state_json,h0_json,goals_geometry_json,provenance_json,identity_quality) VALUES(?,?,?,?,?,?,?,?,?)',
                (state_uid,original['scenario_uid'],s['source_group'],ch,canonical(physical),None,canonical(geometry),canonical(s['provenance']),'CONTENT_EXACT'))
            db.execute('INSERT INTO state_alias VALUES(?,?,?,?)',(original['scenario_uid'],s['alias'],state_uid,EXP))
            states.append(s)
            for old in eta_rows:
                pair=copy.deepcopy(old);pair.update(state_uid=state_uid,state_index=s['index'],split=split,target_seeds=8 if split=='train' else 16)
                pair.pop('parent_state_uid',None);pairs.append(pair)
    p.update(experiment_uid=EXP,experiment='independent_state_support_expansion',
        source_train_families=160,source_validation_families=32,sealed_confirmation_families=64,
        requested_seed_count=7168,confirmation_requested=4096,rollout_budget_new_upper_bound=11264,
        source_rule='Native sample_instance with seeds940031000.. and independently tagged native TRAIN/development/test streams; no outcome filtering',
        primary_question='Does more independent state support permit learning reproducible state-eta preference with the same representations and architectures?',
        frozen_eta_indices=[10,15],model_variants=['eta_only','aggregate_context','entity_response_mean','entity_response_attached'],
        training_sizes=[46,206],training_seeds=[17,23,41],optimizer_and_steps='Same pure-count NLL and1500 steps in both size arms; same initialization and evaluation cadence',
        normalization='TRAIN only',selection='New source VAL only, never the sealed64-family confirmation',
        diagnostics=['controller-by-eta constant prior','state/context replacement','Q contrast accuracy','B15 eligible selection','paired rescue/break'],
        scope='Source-family generalization only. This is not a strict LOSO result or an unseen-eta claim.',
        first_phase='TRAIN+VAL only; final confirmation requires models_frozen.json',
        target_labels_used=False,generator_modified=False,success_semantics_changed=False)
    write(OUT/'states.json',states);write(OUT/'pairs_all.json',pairs);write(OUT/'protocol.json',p)
    trainval=[r for r in pairs if r['split']!='test'];test=[r for r in pairs if r['split']=='test']
    write(OUT/'pairs.json',trainval);write(OUT/'pairs_confirmation.json',test)
    requests=[]
    for c in p['profiles']:
        part=[dict(state_uid=r['state_uid'],eta_uid=r['eta_uid'],controller_uid=c['controller_uid'],seed_keys=[canonical({'future_index':k}) for k in range(r['target_seeds'])]) for r in trainval]
        write(OUT/f'planned_{c["name"]}.json',{'requests':part});requests.extend(part)
        test_requests.extend(dict(state_uid=r['state_uid'],eta_uid=r['eta_uid'],controller_uid=c['controller_uid'],seed_keys=[canonical({'future_index':k}) for k in range(16)]) for r in test)
    assert sum(len(r['seed_keys']) for r in requests)==7168
    write(OUT/'planned_rollouts.json',{'requests':requests});write(OUT/'planned_confirmation.json',{'requests':test_requests})
    write(OUT/'working_state.json',dict(phase='prepared',confirmation_sealed=True,new_rollouts=0))
    with connect() as db,transaction(db):
        db.execute('UPDATE experiment SET protocol_hash=?,code_hash=? WHERE experiment_uid=?',(engine.sha(OUT/'protocol.json'),engine.sha(__file__),EXP))
    print(dict(new_source_train=160,new_source_validation=32,sealed_confirmation=64,first_phase_requested=7168))

def configure():engine.OUT=OUT;engine.EXP=EXP

def validate_plan():
    p=read(OUT/'protocol.json');states={s['uid']:s for s in read(OUT/'states.json')};checked=0
    with connect(True) as db:
      for request in read(OUT/'planned_rollouts.json')['requests']:
        state=db.execute('SELECT * FROM state WHERE state_uid=?',(request['state_uid'],)).fetchone()
        controller=db.execute('SELECT * FROM controller_config WHERE controller_uid=?',(request['controller_uid'],)).fetchone()
        eta=db.execute('SELECT * FROM eta WHERE eta_uid=?',(request['eta_uid'],)).fetchone()
        assert state and controller and eta
        assert state['identity_quality']=='CONTENT_EXACT' and controller['compatibility_quality']=='EXACT_PROFILE'
        assert state['scenario_uid']==controller['scenario_uid']
        assert state['content_hash']==content_hash(states[state['state_uid']]['physical'])
        assert canonical(json.loads(state['physical_state_json']))==canonical(states[state['state_uid']]['physical'])
        checked+=len(request['seed_keys'])
    write(OUT/'identity_preflight_audit.json',dict(requested=checked,identity_checks_passed=True,
        state_scenario_controller_compatible=True,actual_semantic_incompatibilities=0,
        planner_status_note='Legacy lookup_exact returns INCOMPATIBLE whenever no seed rows or aggregates exist; here these are newly registered valid identities with genuinely missing observations, not a semantic mismatch. No signatures relaxed.'))
    print(dict(requested=checked,compatible_registered_identities=True))

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('action',choices=('prepare','filter','run','merge','validate'));p.add_argument('--index',type=int,default=0);a=p.parse_args()
    if a.action=='prepare':prepare()
    elif a.action=='validate':validate_plan()
    else:
        configure()
        if a.action=='filter':engine.filter_numerical()
        elif a.action=='merge':engine.merge()
        else:engine.run(engine.CONTROLLERS[a.index//6],a.index%6)
