"""Freeze the population and the minimal active-neighbor enrichment plan."""
import hashlib,json
from pathlib import Path
ROOT=Path('/home/zhihan/research/Basin_C1');H=ROOT/'diagnostics/orthoflow3_analytic_mindef_stability_v1';C=ROOT/'diagnostics/orthoflow3_local_basin_continuity_v1';B=ROOT/'diagnostics/orthoflow3_bilateral_canonical_audit_v1';M=ROOT/'diagnostics/orthoflow3_representation_migration_v1';D=ROOT/'diagnostics/double_bottleneck_eta3_full_sobol/eta_points.json'
def dig(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()
def main():
 H.mkdir(parents=True,exist_ok=True);(H/'logs').mkdir(exist_ok=True)
 if (H/'state_manifest.json').exists():raise RuntimeError('frozen')
 anchors=json.loads((C/'anchor_manifest.json').read_text())['anchors'];pairs=json.loads((B/'paired_state_manifest.json').read_text())['pairs'];states=[]
 for a,p in zip(sorted(anchors,key=lambda x:x['anchor_rank']),pairs,strict=True):
  states += [{'state_id':a['state_id'],'side':'anchor','pair_rank':a['anchor_rank'],'state_file':a['state_file'],'state_sha256':a['state_sha256'],'absolute_step':a['absolute_step'],'rng_namespace':p['rng_namespace'],'matched_flow_seeds':p['matched_flow_seeds']},{'state_id':p['neighbor_state_id'],'side':'neighbor_t+4','pair_rank':p['pair_rank'],'state_file':p['neighbor_state_file'],'state_sha256':p['neighbor_state_sha256'],'absolute_step':p['neighbor_absolute_step'],'rng_namespace':p['rng_namespace'],'matched_flow_seeds':p['matched_flow_seeds']}]
 (H/'state_manifest.json').write_text(json.dumps({'states':states,'pairs':pairs,'selection':'all 12 frozen anchors and deterministic t+4 neighbors'},indent=2)+'\n')
 p1=json.loads((B/'promotion1_plan.json').read_text())['arms'];p2=json.loads((B/'promotion2_plan.json').read_text())['arms'];p1m={a['anchor_rank']:a for a in p1};p2r={a['anchor_rank'] for a in p2};audit={a['pair_rank']:a for a in json.loads((B/'screen16_audit.json').read_text())};points=json.loads(D.read_text())['points'];arms=[]
 for rank in (1,5,7):
  p=pairs[rank];primary=p1m[rank]['eta_index'];c=sorted([x for x in audit[rank]['screen_candidates'] if x['eta_index']!=primary and x['success16']>=15],key=lambda x:(-x['success16'],x['mean_J'],x['eta_index']))
  if not c:continue
  i=c[0]['eta_index'];arms.append({'arm_id':f'ENRICH__{rank:02d}__{i:03d}','basis_family':'orthoflow3','state_id':p['neighbor_state_id'],'state_file':p['neighbor_state_file'],'state_sha256':p['neighbor_state_sha256'],'absolute_step':p['neighbor_absolute_step'],'rng_namespace':p['rng_namespace'],'eta':points[i]['theta'],'eta_index':i,'seeds':[int(s) for s in p['matched_flow_seeds'][16:64]],'role':'active_neighbor_enrichment','anchor_rank':rank,'offset_steps':4,'probe_id':'ENRICH'})
 plan={'schema':'of3_mindef_enrichment_v1','basis_family':'orthoflow3','selection_rule':'only active-required t+4 neighbors with one B63 candidate; deterministic next candidate by success16 desc, mean successful J asc, eta index','arms':arms};plan['content_sha256']=dig(plan);(H/'enrichment_plan.json').write_text(json.dumps(plan,indent=2,sort_keys=True)+'\n')
 (H/'protocol.md').write_text('# OrthoFlow3 analytical minimum-deformation audit\n\nPopulation: all 12 frozen anchors and their deterministic t+4 real neighbors. Robust feasibility remains B63. True J is the mean per-seed full-continuation `dt * sum ||u_exec-u_safe||^2` over successful seeds, matching the migration canonical implementation. Four no-learning proxies are compared only inside each confirmed robust set.\n')
 auth={'jdef_source':str(M/'run_subset_arms.py'),'accumulation_lines':'143-176','aggregation_source':str(M/'finalize_migration.py'),'canonical_rule':'B63 first; mean J_def over successful continuations; eta index tie break','horizon':'absolute episode horizon 850; no restart','failure_treatment':'failures excluded from mean successful J after B63 feasibility gate','basis_sha256':'51c2cbcc235a5ba9db6f73b3d449e0bc631bfbb0e1ed3184c4fed97c8fa01c38','eta_scales':[0.75,1.0,0.75],'projection_source':str(ROOT/'diagnostics/success_basin_multimodality/exact_projector.py'),'projection_geometry':'Euclidean quadratic projection onto intersection of linear halfspaces and two second-order speed balls; closed convex set'};(H/'authoritative_jdef_manifest.json').write_text(json.dumps(auth,indent=2)+'\n')
 print(json.dumps({'states':len(states),'pairs':len(pairs),'enrichment_arms':len(arms),'new_continuations':sum(len(a['seeds']) for a in arms),'step_upper':sum((850-a['absolute_step'])*len(a['seeds']) for a in arms)},indent=2))
if __name__=='__main__':main()
