#!/usr/bin/env python3
"""Aggregate fresh WIDE, choose the predeclared Direct-eta decision, and manifest outputs."""
from __future__ import annotations
import csv,hashlib,json,platform,statistics,time
from collections import Counter
from pathlib import Path
import numpy as np
ROOT=Path('/home/zhihan/research/Basin_C1');HERE=ROOT/'diagnostics/orthoflow3_direct_eta_baseline_v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def write_csv(path,rows):
 f=path.open('w',newline='');w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows);f.close()
def raw(stem):
 out=[]
 for p in sorted((HERE/'raw'/stem).glob('shard*.jsonl')):
  if p.stem.removeprefix('shard').isdigit():out += [json.loads(x) for x in p.read_text().splitlines() if x.strip()]
 return out
def main():
 began=time.monotonic();fresh=raw('fresh_wide')
 if len(fresh)!=400:raise RuntimeError(('fresh incomplete',len(fresh)))
 rows=[]
 for r in fresh:rows.append({k:r[k] for k in ('episode_index','source_id','controller','outcome','failure_type','success','deadlock','timeout','collision','wall_collision','agent_collision','other_failure','episode_steps','J_def','eta_norm','eta_clipped','minimum_linear_residual','maximum_speed_excess','invalid_actions')})
 write_csv(HERE/'fresh_wide_results.csv',rows);by=__import__('collections').defaultdict(dict)
 for r in fresh:by[r['episode_index']][r['controller']]=r
 rescue=[];breaks=[]
 for i,p in by.items():
  if not p['safety']['success'] and p['direct_eta']['success']:rescue.append((i,p['safety']['failure_type']))
  if p['safety']['success'] and not p['direct_eta']['success']:breaks.append((i,p['direct_eta']['failure_type']))
 def summary(name):
  rr=[r for r in fresh if r['controller']==name];sj=[r['J_def'] for r in rr if r['success']];allj=[r['J_def'] for r in rr]
  return {'episodes':len(rr),'success':sum(r['success'] for r in rr),'deadlock':sum(r['deadlock'] for r in rr),'timeout':sum(r['timeout'] for r in rr),'agent_collision':sum(r['agent_collision'] for r in rr),'wall_collision':sum(r['wall_collision'] for r in rr),'other_failure':sum(r['other_failure'] for r in rr),'successful_J_def_mean':float(np.mean(sj)) if sj else None,'successful_J_def_median':float(np.median(sj)) if sj else None,'overall_J_def_mean':float(np.mean(allj)),'episode_steps_mean':float(np.mean([r['episode_steps'] for r in rr])),'episode_steps_median':float(np.median([r['episode_steps'] for r in rr]))}
 paired={'Safety':summary('safety'),'Direct_eta':summary('direct_eta'),'rescue':len(rescue),'break':len(breaks),'net_success_change':len(rescue)-len(breaks),'rescue_by_safety_failure_type':dict(Counter(x[1] for x in rescue)),'break_by_direct_failure_type':dict(Counter(x[1] for x in breaks)),'paired_episode_count':len(by)};dump(HERE/'fresh_wide_paired_summary.json',paired)
 dr=[r for r in fresh if r['controller']=='direct_eta'];etas=np.asarray([r['eta'] for r in dr]);norms=np.linalg.norm(etas,axis=1);est={'episodes':len(dr),'eta_norm':{'mean':float(norms.mean()),'median':float(np.median(norms)),'p05':float(np.quantile(norms,.05)),'p95':float(np.quantile(norms,.95)),'max':float(norms.max())},'per_dimension':{f'eta{i+1}':{'mean':float(etas[:,i].mean()),'median':float(np.median(etas[:,i])),'min':float(etas[:,i].min()),'max':float(etas[:,i].max()),'p05':float(np.quantile(etas[:,i],.05)),'p95':float(np.quantile(etas[:,i],.95))} for i in range(3)},'clipping_count':sum(r['eta_clipped'] for r in dr),'clipping_frequency':float(np.mean([r['eta_clipped'] for r in dr]))};dump(HERE/'fresh_wide_eta_statistics.json',est)
 held=json.loads((HERE/'heldout_closedloop_summary.json').read_text());n=held['resolved_test_states'];zero_n=sum(1 for _ in csv.DictReader(open(HERE/'zero_false_activation.csv')));active_n=sum(1 for _ in csv.DictReader(open(HERE/'active_target_performance.csv')))
 historical_p0={'cohort':'historical, not paired to this fresh cohort','Safety_success':143,'P0_structured_eta_success':90,'P0_rescue':33,'P0_break':86,'source':'diagnostics/gphi_structured_eta_fresh_wide_v1/primary_metrics.json'}
 strong=(n>0 and held['predicted_B63_states']/n>=.8 and held['zero_harmful_false_activation']<=max(1,int(.1*zero_n)) and (active_n==0 or held['active_success']/active_n>=.7) and paired['Direct_eta']['success']>=paired['Safety']['success'] and paired['break']<=5)
 promising=(n>0 and held['predicted_B63_states']/n>=.5 and paired['Direct_eta']['success']>historical_p0['P0_structured_eta_success'] and paired['Direct_eta']['success']>=paired['Safety']['success'])
 classification='DIRECT_ETA_STRONGLY_SUPPORTED' if strong else ('DIRECT_ETA_PROMISING_BUT_IMPERFECT' if promising else 'DIRECT_ETA_TARGET_REGRESSION_FAILS')
 decision={'classification':classification,'decision_rule':{'strong':'TEST B63 >=80%; zero harmful <=max(1,10%); ACTIVE B63 >=70%; fresh success >= Safety; break <=5','promising':'TEST B63 >=50%, materially better than historical P0, and fresh success >= matched Safety; meaningful breakage is permitted by the requested class'},'heldout':held,'fresh_wide':paired,'historical_p0_context':historical_p0,'orthoflow3_more_viable_than_old_p0':paired['Direct_eta']['success']>historical_p0['P0_structured_eta_success'] and paired['break']<historical_p0['P0_break'],'q_guided_training_status':'not justified as necessary' if classification=='DIRECT_ETA_STRONGLY_SUPPORTED' else ('promising and justified to test, but not yet proven necessary' if classification=='DIRECT_ETA_PROMISING_BUT_IMPERFECT' else 'strongly motivated to test'),'next_experiment':'No actor training automatically. Smallest next test: repeat the frozen Direct-eta checkpoint on one independent fresh WIDE cohort.' if classification=='DIRECT_ETA_STRONGLY_SUPPORTED' else 'Train one otherwise identical G with frozen-Q feasibility loss as a controlled ablation, keeping split and target data fixed.'};dump(HERE/'direct_eta_decision.json',decision)
 runtime_files=list((HERE/'raw').glob('*/*_runtime.json'));runt=[json.loads(p.read_text()) for p in runtime_files];dirs=['zero_completion_plan']+[p.name for p in (HERE/'raw').glob('active_promotion_round*_plan')]+['test_prediction_plan'];new=sum(len(raw(d)) for d in dirs)+400;steps=sum(int(r.get('new_physical_steps',r.get('physical_steps',0))) for r in runt);frozen=json.loads((HERE/'frozen_direct_eta_manifest.json').read_text());stage_wall={d:max(json.loads(p.read_text()).get('wall_seconds',0) for p in (HERE/'raw'/d).glob('*_runtime.json')) for d in dirs+['fresh_wide']};runtime={'reused_continuations':1008,'new_continuations':new,'physical_steps':steps,'training_seconds':frozen['training_seconds'],'rollout_wall_seconds_critical_path_sum':sum(stage_wall.values()),'rollout_stage_wall_seconds':stage_wall,'maximum_gpu_shards':6,'observed_gpu_memory_per_rollout_process_mib_approximately':602,'rollout_cpu_allocation':'2 CPUs/shard, maximum 12 CPUs','training_cpu_allocation':4,'ram_request_per_rollout_shard_gb':14,'maximum_ram_request_across_6_shards_gb':84,'actual_peak_ram':'not exposed; Slurm accounting storage disabled','host':platform.node(),'finalization_seconds':time.monotonic()-began,'stage_runtime_records':runt};dump(HERE/'runtime_statistics.json',runtime)
 hard={'status':'PASS','agent_collisions':sum(r['agent_collision'] for r in fresh),'wall_collisions':sum(r['wall_collision'] for r in fresh),'invalid_actions':sum(r['invalid_actions'] for r in fresh),'minimum_linear_residual':min(r['minimum_linear_residual'] for r in fresh if r['minimum_linear_residual'] is not None),'maximum_speed_excess':max(r['maximum_speed_excess'] for r in fresh if r['maximum_speed_excess'] is not None),'second_projection_authoritative':True};dump(HERE/'hard_safety_checks.json',hard)
 target=json.loads((HERE/'target_resolution_summary.json').read_text());point=json.loads((HERE/'heldout_pointwise_metrics.json').read_text());model=json.loads((HERE/'model_config.json').read_text());sel=json.loads((HERE/'selected_checkpoint.json').read_text())
 report=f'''# OrthoFlow3 Direct-eta baseline v1\n\n## Result\n\n**{classification}**\n\nThe target is `eta*_24-robust-lowJ`: zero when zero is B63, otherwise the minimum mean-successful full-horizon J_def among confirmed B63 candidates in the frozen 24-point cloud. It is **not** an exact global continuous canonical eta.\n\n## Target and model\n\n- Target resolution: `{json.dumps(target,sort_keys=True)}`\n- Source-group leakage: none (exact Q-v2 80/20/20 split).\n- Model: {model['architecture']}, {model['parameter_count']} parameters, selected seed {sel['seed']}.\n- Checkpoint SHA256: `{sel['checkpoint_sha256']}`.\n\n## Held-out TEST\n\n- Pointwise metrics: `{json.dumps(point,sort_keys=True)}`\n- Predicted B63: {held['predicted_B63_states']}/{n}; mean Q64 {held['mean_pred_Q64']:.4f}.\n- Target B63: {held['target_B63_states']}/{n}; zero B63: {held['zero_B63_states']}/{n}.\n- Zero harmful false activations: {held['zero_harmful_false_activation']}; harmless nonzero: {held['zero_harmless_nonzero']}.\n- ACTIVE successes: {held['active_success']}; basin misses: {held['active_basin_miss']}; near-zero misses: {held['active_near_zero_miss']}.\n- Read-only frozen-Q mean on Direct-eta successes/misses: {held['Qhat_mean_on_pred_success']} / {held['Qhat_mean_on_pred_miss']}.\n\n## Fresh WIDE 200\n\n- Safety: {paired['Safety']['success']}/200 success, {paired['Safety']['deadlock']} deadlock, {paired['Safety']['timeout']} timeout, {paired['Safety']['agent_collision']+paired['Safety']['wall_collision']} collisions.\n- Direct-eta: {paired['Direct_eta']['success']}/200 success, {paired['Direct_eta']['deadlock']} deadlock, {paired['Direct_eta']['timeout']} timeout, {paired['Direct_eta']['agent_collision']+paired['Direct_eta']['wall_collision']} collisions.\n- Rescue / break / net: {paired['rescue']} / {paired['break']} / {paired['net_success_change']}.\n- Successful mean J_def, Safety / Direct-eta: {paired['Safety']['successful_J_def_mean']} / {paired['Direct_eta']['successful_J_def_mean']}.\n- Eta norm median/mean/max: {est['eta_norm']['median']:.4f} / {est['eta_norm']['mean']:.4f} / {est['eta_norm']['max']:.4f}; clipping {est['clipping_count']}/200.\n- Hard safety: zero collisions and invalid actions; the second projection remained authoritative.\n\nHistorical P0 context (different cohort, not paired): 90/200 success, 33 rescues, and 86 breaks versus its 143/200 Safety reference.\n\n## Interpretation\n\nOrthoFlow3 Direct-eta is judged substantially more viable than the historical P0 step-0 controller: **{decision['orthoflow3_more_viable_than_old_p0']}**. Q-guided training status: **{decision['q_guided_training_status']}**.\n\nSmallest justified next experiment: {decision['next_experiment']}\n\nNo Q, J, Direct-g, gate, mixture, flow, recovery, or cadence model was trained or used to alter Direct-eta behavior.\n''';(HERE/'direct_eta_report.md').write_text(report)
 files=[]
 for p in sorted(HERE.iterdir()):
  if p.is_file() and p.name!='manifest.json':files.append({'path':p.name,'sha256':sha(p),'bytes':p.stat().st_size})
 dump(HERE/'manifest.json',{'schema':'orthoflow3_direct_eta_baseline_v1','classification':classification,'orthoflow3_implementation':str(ROOT/'diagnostics/double_bottleneck_eta_basis_redesign/tools/bases.py'),'orthoflow3_sha256':'51c2cbcc235a5ba9db6f73b3d449e0bc631bfbb0e1ed3184c4fed97c8fa01c38','files':files,'raw_data_retained':True});print(json.dumps({'decision':decision,'runtime':{k:v for k,v in runtime.items() if k!='stage_runtime_records'}},indent=2))
if __name__=='__main__':main()
